name: Build and Release Process

on:
  push:
    branches:
      - 'main'
      - 'master'
  repository_dispatch:
    types: [ build ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK ${{ matrix.java }}
        uses: coursier/setup-action@main
        with:
          jvm: corretto:${{ matrix.java }}
          apps: sbt scala scalac
      - name: Run tests
        run: sbt test
  scripted-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK ${{ matrix.java }}
        uses: coursier/setup-action@main
        with:
          jvm: corretto:${{ matrix.java }}
          apps: sbt scala scalac
      - name: Run tests
        run: sbt ^scripted
  release:
    needs:
      - scripted-test
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ADMIN_TOKEN }}
      - id: install-secret-key
        name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.PGP_SECRET_KEY }}") | gpg --batch --import
      - name: Set up JDK
        uses: coursier/setup-action@main
        with:
          jvm: corretto:21
          apps: sbt scala scalac
      - name: Diagnose git fetch (temporary)
        run: |
          git remote -v
          git fetch origin -v
      - name: Diagnose sbt-release vcs checks (temporary)
        run: sbt diagnose-vcs
      - name: Release
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSWORD }}
          PGP_SECRET: ${{ secrets.PGP_SECRET_KEY }}
        run: |
          git config --global user.email "ci@quadstingray.dev"
          git config --global user.name "QuadStingray CI"
          sbt -Dsbt.supershell=false ci-release
