name: Test Process

on:
  push:
    branches-ignore:
      - 'main'
      - 'master'
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK ${{ matrix.java }}
        uses: coursier/setup-action@main
        with:
          jvm: corretto:${{ matrix.java }}
          apps: sbt scala scalac
      - name: Run tests
        run: sbt test
  scripted-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK ${{ matrix.java }}
        uses: coursier/setup-action@main
        with:
          jvm: corretto:${{ matrix.java }}
          apps: sbt scala scalac
      - name: Run tests
        run: sbt ^scripted
